server:
  port: 9090

spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false

    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/join
      username: root
      password: 1234
      hikari:
        maximum-pool-size: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml